// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiProjects.Data;

#nullable disable

namespace WebApiProjects.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702150702_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiProjects.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer Service"
                        });
                });

            modelBuilder.Entity("WebApiProjects.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.doe@example.com",
                            Name = "John Doe",
                            Phone = "123-456-7890",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            Phone = "987-654-3210",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "michael.johnson@example.com",
                            Name = "Michael Johnson",
                            Phone = "555-123-4567",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "emily.davis@example.com",
                            Name = "Emily Davis",
                            Phone = "444-789-1234",
                            Salary = 53000m
                        },
                        new
                        {
                            Id = 5,
                            Email = "david.wilson@example.com",
                            Name = "David Wilson",
                            Phone = "333-222-1111",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "sophia.martinez@example.com",
                            Name = "Sophia Martinez",
                            Phone = "777-888-9999",
                            Salary = 58000m
                        });
                });

            modelBuilder.Entity("WebApiProjects.Models.Employee", b =>
                {
                    b.HasOne("WebApiProjects.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebApiProjects.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
